version: 2.1
jobs:
  terraform_init:
    docker: 
      - image: hashicorp/terraform:light # the primary container, where your job's commands are run
      - image: ubuntu:18.04
      
    working_directory: /workspace
    
    steps:
      - checkout # check out the code in the project directory
      - run:
          name: terraform init
          command: |
            terraform init
            
workflows:
  version: 2.1
  terraform:
    jobs:
      - terraform_init
