version: 2.1
jobs:
  terraform_plan:
    docker: 
      - image: hashicorp/terraform:light # the primary container, where your job's commands are run
      
    working_directory: /workspace
    
    steps:
      - checkout # check out the code in the project directory
      - run:
          name: terraform init & plan
          command: |
            terraform init
            terraform plan
            
workflows:
  version: 2.1
  terraform:
    jobs:
      - terraform_plan
